// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.migration.version", 172);
user_pref("browser.newtabpage.activity-stream.impressionId", "{04160f6e-a3b6-4b30-9f61-56e0967990c0}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.policies.runOncePerModification.displayBookmarksToolbar", "never");
user_pref("browser.policies.runOncePerModification.extensionsUninstall", "[\"google@search.mozilla.org\",\"bing@search.mozilla.org\",\"amazondotcom@search.mozilla.org\",\"ebay@search.mozilla.org\",\"twitter@search.mozilla.org\",\"webcompat@mozilla.org\",\"screenshots@mozilla.org\",\"pictureinpicture@mozilla.org\",\"formautofill@mozilla.org\"]");
user_pref("browser.privacySegmentation.createdShortcut", true);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.lastColdStartupCheck", 1786687192);
user_pref("browser.termsofuse.prefMigrationCheck", true);
user_pref("browser.theme.content-theme", 0);
user_pref("browser.theme.toolbar-theme", 0);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"vertical-spacer\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"reset-pbm-toolbar-button\",\"unified-extensions-button\",\"new-tab-button\",\"alltabs-button\",\"personal-bookmarks\",\"ublock0_raymondhill_net-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\"],\"vertical-tabs\":[],\"PersonalToolbar\":[]},\"seen\":[\"reset-pbm-toolbar-button\",\"developer-button\",\"ublock0_raymondhill_net-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"TabsToolbar\",\"vertical-tabs\",\"PersonalToolbar\"],\"currentVersion\":24,\"newElementCount\":2}");
user_pref("captchadetection.lastSubmission", 1786687);
user_pref("datareporting.dau.cachedUsageProfileGroupID", "b0bacafe-b0ba-cafe-b0ba-cafeb0bacafe");
user_pref("datareporting.dau.cachedUsageProfileID", "beefbeef-beef-beef-beef-beeefbeefbee");
user_pref("datareporting.policy.firstRunURL", "https://www.mozilla.org/privacy/firefox/");
user_pref("distribution.iniFile.exists.appversion", "152.0.4-beta.28");
user_pref("distribution.iniFile.exists.value", false);
user_pref("dom.filesystem.pathcheck.disabled", true);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.colorway-builtin-themes-cleanup", 1);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.lastAppBuildId", "20260719045835");
user_pref("extensions.lastAppVersion", "152.0.4-beta.28");
user_pref("extensions.lastPlatformVersion", "152.0.4");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.uuids", "{\"data-leak-blocker@mozilla.com\":\"40f3a062-f582-42cb-b036-5843983dc45e\",\"formautofill@mozilla.org\":\"c7cc8e8b-a98b-4971-bcf0-5e39f45b74f8\",\"ipp-activator@mozilla.com\":\"e487ea5f-fe2c-4c6c-a46a-14c3fdc4f68e\",\"pictureinpicture@mozilla.org\":\"92022bc3-dd8d-4b3b-86c6-0c1bac20b372\",\"addons-search-detection@mozilla.com\":\"b88f427c-f766-4a99-a2e5-7f8514f35ef8\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"newtab@mozilla.org\":\"872253e8-7bf4-4eb9-9ed1-f202ac1cb2e8\",\"firefox-compact-dark@mozilla.org\":\"be9c12e7-6198-4745-9117-f2e1d3254f2e\",\"uBlock0@raymondhill.net\":\"40fd8ac9-4444-448a-bf93-098dd93002f1\"}");
user_pref("font.system.whitelist", "Arial,Calibri,Cambria Math,Consolas,Courier New,Georgia,Nirmala UI,Segoe UI,Tahoma,Times New Roman,Trebuchet MS,Verdana,新宋体,宋体,Leelawadee UI,Gadugi,Myanmar Text,Constantia,Symbol,Yu Gothic UI Semibold,Lucida Console,Yu Gothic Medium,Segoe UI Symbol,ＭＳ ゴシック,細明體_HKSCS-ExtB,游ゴシック Medium,Candara,Wingdings,Microsoft Tai Le,新細明體-ExtB,Calibri Light,Twemoji Mozilla,微軟正黑體,MS PGothic,微软雅黑 Light,Lucida Sans Unicode,Segoe UI Black,Yu Gothic UI,Leelawadee UI Semilight,MingLiU_HKSCS-ExtB,Malgun Gothic,Microsoft JhengHei,ＭＳ Ｐゴシック,Sitka Text,Microsoft JhengHei UI,MS UI Gothic,Microsoft Himalaya,Palatino Linotype,Microsoft YaHei UI,Segoe Script,游ゴシック,Ink Free,Corbel Light,Microsoft Sans Serif,Segoe UI Historic,Segoe UI Variable,Comic Sans MS,Gabriola");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.getdisplaymedia.screencapturekit.enabled", false);
user_pref("media.getdisplaymedia.screencapturekit.picker.enabled", false);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
user_pref("network.cookie.validation.lastEpoch", 1);
user_pref("nimbus.profileId", "8e7ab28b-528e-41d1-af6a-59fbc036b05c");
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.clearOnShutdown_v2.formdata", true);
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs3", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("sanity-test.device-id", "0x67df");
user_pref("sanity-test.driver-version", "31.0.21924.61");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20260719045835");
user_pref("security.sandbox.warn_unprivileged_namespaces", false);
user_pref("sidebar.backupState", "{\"command\":\"\",\"panelOpen\":false,\"bookmarksExpandedFolders\":[],\"launcherExpanded\":false,\"launcherVisible\":false}");
user_pref("sidebar.visibility", "hide-sidebar");
user_pref("toolkit.profiles.newProfileSubmitted", true);
user_pref("toolkit.profiles.storeID", "0373ac08");
user_pref("toolkit.startup.last_success", 1786687189);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.cachedProfileGroupID", "decafdec-afde-cafd-ecaf-decafdecafde");
user_pref("toolkit.telemetry.previousBuildID", "20260719045835");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("webgl.force-enabled", true);
